using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace mcsharpbot.communication
{
    public enum Blocks
    {
        Air = 0,
        Stone = 1,
        Grass = 2,
        Dirt = 3,
        Cobblestone = 4,
        Planks = 5,
        Sapling = 6,
        Bedrock = 7,
        WaterStill = 8,
        WaterMoving = 9,
        LavaStill = 10,
        LavaMoving = 11,
        Sand = 12,
        Gravel = 13,
        OreGold = 14,
        OreIron = 15,
        OreCoal = 16,
        Wood = 17,
        Leaves = 18,
        Sponge = 19,
        Glass = 20,
        OreLapis = 21,
        BlockLapis = 22,
        Dispenser = 23,
        SandStone = 24,
        MusicBlock = 25,
        Cloth = 35,
        PlantYellow = 37,
        PlantRed = 38,
        MushroomBrown = 39,
        MushroomRed = 40,
        BlockGold = 41,
        BlockSteel = 42,
        StairDouble = 43,
        StairSingle = 44,
        Brick = 45,
        TNT = 46,
        BookShelf = 47,
        CobblestoneMossy = 48,
        Obsidian = 49,
        TorchWood = 50,
        Fire = 51,
        MobSpawner = 52,
        StairCompactPlanks = 53,
        Chest = 54,
        RedstoneWire = 55,
        OreDiamond = 56,
        BlockDiamond = 57,
        Workbench = 58,
        Crops = 59,
        TilledField = 60,
        StoneOvenIdle = 61,
        StoneOvenActive = 62,
        SignPost = 63,
        DoorWood = 64,
        Ladder = 65,
        MinecartTrack = 66,
        StairCompactCobblestone = 67,
        SignWall = 68,
        Lever = 69,
        PressurePlateStone = 70,
        DoorSteel = 71,
        PressurePlatePlanks = 72,
        OreRedstone = 73,
        OreRedstoneGlowing = 74,
        TorchRedstoneIdle = 75,
        TorchRedstoneActive = 76,
        Button = 77,
        Snow = 78,
        BlockIce = 79,
        BlockSnow = 80,
        Cactus = 81,
        BlockClay = 82,
        Reed = 83,
        Jukebox = 84,
        Fence = 85,
        Pumpkin = 86,
        HellRock = 87,
        HellSand = 88,
        LightStone = 89,
        Portal = 90,
        PumpkinLantern = 91,
        Cake = 92
    }
}
