using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;

namespace mcsharpbot.communication
{
    public class BlockColors
    {
        public static Color Air = Color.Transparent;
        public static Color Stone = Color.Gray;
        public static Color Grass = Color.Green;
        public static Color Dirt = Color.Brown;
        public static Color Cobblestone = Color.DarkSlateGray;
        public static Color Planks = Color.SandyBrown;
        public static Color Sapling = Color.SeaGreen;
        public static Color Bedrock = Color.DarkGray;
        public static Color WaterStill = Color.DarkBlue;
        public static Color WaterMoving = Color.Blue;
        public static Color LavaStill = Color.OrangeRed;
        public static Color LavaMoving = Color.Orange;
        public static Color Sand = Color.LightGoldenrodYellow;
        public static Color Gravel = Color.LightSlateGray;
        public static Color OreGold = Color.Gold;
        public static Color OreIron = Color.SlateGray;
        public static Color OreCoal = Color.Black;
        public static Color Wood = Color.SaddleBrown;
        public static Color Leaves = Color.ForestGreen;
        public static Color Sponge = Color.YellowGreen;
        public static Color Glass = Color.WhiteSmoke;
        public static Color OreLapis = Color.MediumSlateBlue;
        public static Color BlockLapis = Color.MidnightBlue;
        public static Color Dispenser = Color.DarkSlateGray;
        public static Color SandStone = Color.GreenYellow;
        public static Color MusicBlock = Color.RosyBrown;
        public static Color Cloth = Color.Salmon;
        public static Color PlantYellow = Color.Yellow;
        public static Color PlantRed = Color.Red;
        public static Color MushroomBrown = Color.Brown;
        public static Color MushroomRed = Color.Red;
        public static Color BlockGold = Color.Gold;
        public static Color BlockSteel = Color.Gray;
        public static Color StairDouble = Color.Brown;
        public static Color StairSingle = Color.Brown;
        public static Color Brick = Color.IndianRed;
        public static Color TNT = Color.MediumVioletRed;
        public static Color BookShelf = Color.Brown;
        public static Color CobblestoneMossy = Color.Green;
        public static Color Obsidian = Color.Black;
        public static Color TorchWood = Color.OrangeRed;
        public static Color Fire = Color.OrangeRed;
        public static Color MobSpawner = Color.LightGreen;
        public static Color StairCompactPlanks = Color.Brown;
        public static Color Chest = Color.Brown;
        public static Color RedstoneWire = Color.PaleVioletRed;
        public static Color OreDiamond = Color.CornflowerBlue;
        public static Color BlockDiamond = Color.RoyalBlue;
        public static Color Workbench = Color.Brown;
        public static Color Crops = Color.LawnGreen;
        public static Color TilledField = Color.SandyBrown;
        public static Color StoneOvenIdle = Color.DarkGray;
        public static Color StoneOvenActive = Color.DarkGray;
        public static Color SignPost = Color.Brown;
        public static Color DoorWood = Color.Brown;
        public static Color Ladder = Color.Brown;
        public static Color MinecartTrack = Color.Gray;
        public static Color StairCompactCobblestone = Color.LightSlateGray;
        public static Color SignWall = Color.Brown;
        public static Color Lever = Color.DimGray;
        public static Color PressurePlateStone = Color.LightSlateGray;
        public static Color DoorSteel = Color.DarkSlateGray;
        public static Color PressurePlatePlanks = Color.Brown;
        public static Color OreRedstone = Color.PaleVioletRed;
        public static Color OreRedstoneGlowing = Color.MediumVioletRed;
        public static Color TorchRedstoneIdle = Color.DarkRed;
        public static Color TorchRedstoneActive = Color.OrangeRed;
        public static Color Button = Color.Gray;
        public static Color Snow = Color.WhiteSmoke;
        public static Color BlockIce = Color.CadetBlue;
        public static Color BlockSnow = Color.White;
        public static Color Cactus = Color.Green;
        public static Color BlockClay = Color.LightSlateGray;
        public static Color Reed = Color.PaleGreen;
        public static Color Jukebox = Color.Brown;
        public static Color Fence = Color.Brown;
        public static Color Pumpkin = Color.Orange;
        public static Color HellRock = Color.IndianRed;
        public static Color HellSand = Color.SandyBrown;
        public static Color LightStone = Color.LightGoldenrodYellow;
        public static Color Portal = Color.Purple;
        public static Color PumpkinLantern = Color.OrangeRed;
        public static Color Cake = Color.Wheat;

    }
}
